Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/asyncio/base_events.py", line 686, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
heading = "Kovats+Retention+Index"      # spaces are replaced with "+"

num_page_total = 80
data = [None] * num_page_total

for i in range(num_page_total):
    
    page_curr = i + 1
    url = base + "/annotations/heading/JSON?heading=" + heading + "&page=" + str(page_curr)
    data[i] = requests.get(url).json()
    
    if page_curr % 5 == 0 :
        print("Getting data for page", page_curr)
    
    time.sleep(0.2)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mProtocolError[0m                             Traceback (most recent call last)
File [0;32m/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/requests/models.py:820[0m, in [0;36mResponse.iter_content.<locals>.generate[0;34m()[0m
[1;32m    819[0m [38;5;28;01mtry[39;00m:
[0;32m--> 820[0m     [38;5;28;01myield from[39;00m [38;5;28mself[39m[38;5;241m.[39mraw[38;5;241m.[39mstream(chunk_size, decode_content[38;5;241m=[39m[38;5;28;01mTrue[39;00m)
[1;32m    821[0m [38;5;28;01mexcept[39;00m ProtocolError [38;5;28;01mas[39;00m e:

File [0;32m/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/response.py:1057[0m, in [0;36mHTTPResponse.stream[0;34m(self, amt, decode_content)[0m
[1;32m   1056[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39mchunked [38;5;129;01mand[39;00m [38;5;28mself[39m[38;5;241m.[39msupports_chunked_reads():
[0;32m-> 1057[0m     [38;5;28;01myield from[39;00m [38;5;28mself[39m[38;5;241m.[39mread_chunked(amt, decode_content[38;5;241m=[39mdecode_content)
[1;32m   1058[0m [38;5;28;01melse[39;00m:

File [0;32m/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/response.py:1206[0m, in [0;36mHTTPResponse.read_chunked[0;34m(self, amt, decode_content)[0m
[1;32m   1205[0m [38;5;28;01mwhile[39;00m [38;5;28;01mTrue[39;00m:
[0;32m-> 1206[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_update_chunk_length[49m[43m([49m[43m)[49m
[1;32m   1207[0m     [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39mchunk_left [38;5;241m==[39m [38;5;241m0[39m:

File [0;32m/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/response.py:1136[0m, in [0;36mHTTPResponse._update_chunk_length[0;34m(self)[0m
[1;32m   1134[0m [38;5;28;01melse[39;00m:
[1;32m   1135[0m     [38;5;66;03m# Truncated at start of next chunk[39;00m
[0;32m-> 1136[0m     [38;5;28;01mraise[39;00m ProtocolError([38;5;124m"[39m[38;5;124mResponse ended prematurely[39m[38;5;124m"[39m) [38;5;28;01mfrom[39;00m [38;5;28;01mNone[39;00m

[0;31mProtocolError[0m: Response ended prematurely

During handling of the above exception, another exception occurred:

[0;31mChunkedEncodingError[0m                      Traceback (most recent call last)
Cell [0;32mIn[20], line 10[0m
[1;32m      8[0m page_curr [38;5;241m=[39m i [38;5;241m+[39m [38;5;241m1[39m
[1;32m      9[0m url [38;5;241m=[39m base [38;5;241m+[39m [38;5;124m"[39m[38;5;124m/annotations/heading/JSON?heading=[39m[38;5;124m"[39m [38;5;241m+[39m heading [38;5;241m+[39m [38;5;124m"[39m[38;5;124m&page=[39m[38;5;124m"[39m [38;5;241m+[39m [38;5;28mstr[39m(page_curr)
[0;32m---> 10[0m data[i] [38;5;241m=[39m [43mrequests[49m[38;5;241;43m.[39;49m[43mget[49m[43m([49m[43murl[49m[43m)[49m[38;5;241m.[39mjson()
[1;32m     12[0m [38;5;28;01mif[39;00m page_curr [38;5;241m%[39m [38;5;241m5[39m [38;5;241m==[39m [38;5;241m0[39m :
[1;32m     13[0m     [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mGetting data for page[39m[38;5;124m"[39m, page_curr)

File [0;32m/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/requests/api.py:73[0m, in [0;36mget[0;34m(url, params, **kwargs)[0m
[1;32m     62[0m [38;5;28;01mdef[39;00m [38;5;21mget[39m(url, params[38;5;241m=[39m[38;5;28;01mNone[39;00m, [38;5;241m*[39m[38;5;241m*[39mkwargs):
[1;32m     63[0m [38;5;250m    [39m[38;5;124mr[39m[38;5;124;03m"""Sends a GET request.[39;00m
[1;32m     64[0m 
[1;32m     65[0m [38;5;124;03m    :param url: URL for the new :class:`Request` object.[39;00m
[0;32m   (...)[0m
[1;32m     70[0m [38;5;124;03m    :rtype: requests.Response[39;00m
[1;32m     71[0m [38;5;124;03m    """[39;00m
[0;32m---> 73[0m     [38;5;28;01mreturn[39;00m [43mrequest[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mget[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43murl[49m[43m,[49m[43m [49m[43mparams[49m[38;5;241;43m=[39;49m[43mparams[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/requests/api.py:59[0m, in [0;36mrequest[0;34m(method, url, **kwargs)[0m
[1;32m     55[0m [38;5;66;03m# By using the 'with' statement we are sure the session is closed, thus we[39;00m
[1;32m     56[0m [38;5;66;03m# avoid leaving sockets open which can trigger a ResourceWarning in some[39;00m
[1;32m     57[0m [38;5;66;03m# cases, and look like a memory leak in others.[39;00m
[1;32m     58[0m [38;5;28;01mwith[39;00m sessions[38;5;241m.[39mSession() [38;5;28;01mas[39;00m session:
[0;32m---> 59[0m     [38;5;28;01mreturn[39;00m [43msession[49m[38;5;241;43m.[39;49m[43mrequest[49m[43m([49m[43mmethod[49m[38;5;241;43m=[39;49m[43mmethod[49m[43m,[49m[43m [49m[43murl[49m[38;5;241;43m=[39;49m[43murl[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/requests/sessions.py:589[0m, in [0;36mSession.request[0;34m(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)[0m
[1;32m    584[0m send_kwargs [38;5;241m=[39m {
[1;32m    585[0m     [38;5;124m"[39m[38;5;124mtimeout[39m[38;5;124m"[39m: timeout,
[1;32m    586[0m     [38;5;124m"[39m[38;5;124mallow_redirects[39m[38;5;124m"[39m: allow_redirects,
[1;32m    587[0m }
[1;32m    588[0m send_kwargs[38;5;241m.[39mupdate(settings)
[0;32m--> 589[0m resp [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43msend[49m[43m([49m[43mprep[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43msend_kwargs[49m[43m)[49m
[1;32m    591[0m [38;5;28;01mreturn[39;00m resp

File [0;32m/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/requests/sessions.py:746[0m, in [0;36mSession.send[0;34m(self, request, **kwargs)[0m
[1;32m    743[0m         [38;5;28;01mpass[39;00m
[1;32m    745[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m stream:
[0;32m--> 746[0m     [43mr[49m[38;5;241;43m.[39;49m[43mcontent[49m
[1;32m    748[0m [38;5;28;01mreturn[39;00m r

File [0;32m/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/requests/models.py:902[0m, in [0;36mResponse.content[0;34m(self)[0m
[1;32m    900[0m         [38;5;28mself[39m[38;5;241m.[39m_content [38;5;241m=[39m [38;5;28;01mNone[39;00m
[1;32m    901[0m     [38;5;28;01melse[39;00m:
[0;32m--> 902[0m         [38;5;28mself[39m[38;5;241m.[39m_content [38;5;241m=[39m [38;5;124;43mb[39;49m[38;5;124;43m"[39;49m[38;5;124;43m"[39;49m[38;5;241;43m.[39;49m[43mjoin[49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43miter_content[49m[43m([49m[43mCONTENT_CHUNK_SIZE[49m[43m)[49m[43m)[49m [38;5;129;01mor[39;00m [38;5;124mb[39m[38;5;124m"[39m[38;5;124m"[39m
[1;32m    904[0m [38;5;28mself[39m[38;5;241m.[39m_content_consumed [38;5;241m=[39m [38;5;28;01mTrue[39;00m
[1;32m    905[0m [38;5;66;03m# don't need to release the connection; that's been handled by urllib3[39;00m
[1;32m    906[0m [38;5;66;03m# since we exhausted the data.[39;00m

File [0;32m/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/requests/models.py:822[0m, in [0;36mResponse.iter_content.<locals>.generate[0;34m()[0m
[1;32m    820[0m     [38;5;28;01myield from[39;00m [38;5;28mself[39m[38;5;241m.[39mraw[38;5;241m.[39mstream(chunk_size, decode_content[38;5;241m=[39m[38;5;28;01mTrue[39;00m)
[1;32m    821[0m [38;5;28;01mexcept[39;00m ProtocolError [38;5;28;01mas[39;00m e:
[0;32m--> 822[0m     [38;5;28;01mraise[39;00m ChunkedEncodingError(e)
[1;32m    823[0m [38;5;28;01mexcept[39;00m DecodeError [38;5;28;01mas[39;00m e:
[1;32m    824[0m     [38;5;28;01mraise[39;00m ContentDecodingError(e)

[0;31mChunkedEncodingError[0m: Response ended prematurely

